# Generated by Django 5.0.6 on 2024-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_ordermodel_area_alter_ordermodel_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='area',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='county',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='second_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='sub_county',
            field=models.CharField(default='', max_length=30),
        ),
    ]
