# Generated by Django 5.0.6 on 2024-06-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
